### ISSUE TITLE
Samples not rdy for build?

### ISSUE THREAD

**Issue by Bia10** [PieroCastillo/Lettuce#2]
CustomWindow sample:
![image](https://user-images.githubusercontent.com/2548763/125598236-644b1482-4304-4dbf-81f0-a7ffd46e8a76.png)

2D Sample:
![image](https://user-images.githubusercontent.com/2548763/125598285-c7088d24-65a2-472c-81ad-4e5423799f6f.png)

**Comment by PieroCastillo** [comment]
It's in building, now doesn't work..., But with the last commit compiles ok, (now there are some artifacts)

**Comment by Bia10** [comment]
nope still not working

![image](https://user-images.githubusercontent.com/2548763/126542667-d03c88be-ed7d-4b23-866f-4bcd636cbc91.png)

works well on vultaik

![image](https://user-images.githubusercontent.com/2548763/126542815-163834f3-5346-4539-b9c0-e9387f0d4a61.png)

**Comment by PieroCastillo** [comment]
now works without problems 
![image](https://user-images.githubusercontent.com/39932324/127924930-9cc7d92e-a1ca-4cad-b297-3e2a1e680004.png)
